apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha-home-assistant
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: ha
      app.kubernetes.io/name: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ha
        app.kubernetes.io/name: home-assistant
    spec:
      containers:
      - image: homeassistant/home-assistant:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: api
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: home-assistant
        ports:
        - containerPort: 8123
          name: api
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: api
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        command:
          - bash
          - -ec
          - |
            echo "getting HA configs from GIT"
            cd /tmp
            #git clone https://github.com/vavallee/micro-kubernetes.git
            # Remote Repo looks good
            git clone https://github.com/bjw-s/hass-config.git
            echo "moving configs to /config"
            cp -R /tmp/hass-config/* /config
            python3 -m homeassistant --config /config
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: ha-home-assistant
