homeassistant:
  name: Olivet
  latitude: !env_var latitude
  longitude: !env_var longitude
  unit_system: metric
  time_zone: !env_var time_zone
  external_url: !env_var external_url
default_config:
tts:
  - platform: google_translate
sensor:
  - platform: darksky
    api_key: !env_var darksky_api_key
    forecast:
      - 0
      - 1
      - 2
    hourly_forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - temperature
      - humidity
      - wind_speed
      - wind_gust
      - pressure

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
logger:
  default: info
  logs:
    homeassistant.components.http.ban: warning
influxdb:
  host: 192.168.1.4
speedtestdotnet:
  server_id: 21275
